# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build https-github.com-base44dev-fs-ai
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install --global pnpm
          pnpm install
          pnpm build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{Hume_API_Key}
          service-host: api-eu.ionos.space
          project-id: ef6b6dcc-61ec-45e6-b56a-5f824ecde83c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/https-github.com-base44dev-fs-ai/config.yaml
          action: upload
